### ISSUE TITLE
./bootstrap.sh [platform detection failure on macos]

### ISSUE THREAD

**Issue by nbbaier** [CDSoft/luax#2]
Getting the following output when running `./bootstrap.sh`:

```
10:52 ~/luax/ λ master ./bootstrap.sh

\e[44mStep 0: install dependencies\e[0m

Downloading https://ziglang.org/download/0.12.0/zig-macos-aarch64-0.12.0.tar.xz


\e[44mStep 1: bootstrap a Lua interpreter and generate build.ninja\e[0m

[0/1] Generate build.ninja
.build/boot/lua: $bang:libluax/sys/sys.lua:46: Unknown architecture
stack traceback:
	[C]: in function 'assert'
	$bang:libluax/sys/sys.lua:46: in function <$bang:libluax/sys/sys.lua:40>
	$bang:libluax/sys/sys.lua:47: in main chunk
	[C]: in function 'require'
	$bang:libluax/fs/_fs.lua:28: in main chunk
	[C]: in function 'require'
	$bang:libluax/fs/fs.lua:28: in main chunk
	[C]: in function 'require'
	tools/bang.lua:11850: in main chunk
	[C]: in ?
FAILED: build.ninja
.build/boot/lua tools/bang.lua -o build.ninja build.lua && echo You can now execute ninja to build LuaX
ninja: build stopped: subcommand failed.
```

**Comment by CDSoft** [comment]
Thanks for the report.
Sorry, LuaX is mainly tested on Linux... So I guess I can make macos executables from linux but not from macos ;-)

Are you using the latest master version?

Could you please post the result of the following commands?

``` sh
.build/boot/lua -e 'print(package.cpath)'
.build/boot/lua -e 'print(package.config)'
uname -m
uname -s
```

**Comment by CDSoft** [comment]
You can also try the version in the `dev` branch. It uses a slightly different method to detect the OS.

**Comment by CDSoft** [comment]
I pushed a fix to detect the OS in `sys.lua` the same way than `install_zig.sh` (which seems to work on macos since you could install zig and compile lua).

The version 6.0.20 should work better on macos.

**Comment by nbbaier** [comment]
I'm now running into this issue:

```
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.
```
This is my java version

``` sh
17:25 ~/ λ java --version
java 21.0.2 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)
```

**Comment by CDSoft** [comment]
I guess `apt` on macos is not the Debian packet manager?
I'll try to use the right packet manager instead of trying them all.

You can also install ninja yourself before running `bootstrap.sh`
(but this looks strange because in your first message ninja seems to be already installed)

update: The version 6.0.21 only tries `brew` on macos.

**Comment by CDSoft** [comment]
I'm closing this issue since the OS detection has been changed in `bootstrap.sh`. Do not hesitate to open a new issue if the compilation does not work on mac.
