### ISSUE TITLE
any benchmark against the rest?

### ISSUE THREAD

**Issue by sprappcom** [CDSoft/luax#3]
as titled

**Comment by CDSoft** [comment]
There is no LuaX specific benchmark. LuaX is based on Lua 5.4.7 and should be as fast as Lua 5.4.7.

May you please explain what kind of benchmark (speed, features...) you would like to have or perform ? And what the "rest" is?

**Comment by CDSoft** [comment]
I'm closing this issue. Do not hesitate to reopen it if you need/have more information.
